name: CI testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_notebook:
    name: Run simulation notebook
    runs-on: "ubuntu-latest"
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: setup environment
        run: python -m pip install -r requirements_3.12.txt
      - name: download nuclear data
        run: |
            mkdir -p ~/nuclear_data
            wget -q -O - https://anl.box.com/shared/static/uhbxlrx7hvxqw27psymfbhi7bx7s6u6a.xz | tar -C ~/nuclear_data -xJ
            mv ~/nuclear_data/endfb-viii.0-hdf5/cross_sections.xml ~/nuclear_data
            mv ~/nuclear_data/endfb-viii.0-hdf5/photon ~/nuclear_data
            mv ~/nuclear_data/endfb-viii.0-hdf5/neutron ~/nuclear_data
            # TODO move to TENDL 2017 for a like ofr like comparison with fispact results
      - name: run notebook
        run: |
            jupyter nbconvert --to notebook --execute compare.ipynb --inplace
      - name: build jupyter-book
        run: |
            jupyter-book build .

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_build/html"
          name: github-pages

      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
